"""empty message

Revision ID: e8dd7a097192
Revises: 7f149ff6ded4
Create Date: 2025-03-24 19:28:20.342155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dd7a097192'
down_revision = '7f149ff6ded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_fkey', type_='foreignkey')
        batch_op.drop_column('gender')
        batch_op.drop_column('character_description_text')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('is_active')
        batch_op.drop_column('vehicles')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('starships')
        batch_op.drop_column('species')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')
        batch_op.drop_column('films')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('planet_description_text')
        batch_op.drop_column('residents')
        batch_op.drop_column('diameter')
        batch_op.drop_column('gravity')
        batch_op.drop_column('population')
        batch_op.drop_column('is_active')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('films')
        batch_op.drop_column('surface_water')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_water', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('films', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('residents', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_description_text', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('starships', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicles', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('character_description_text', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_homeworld_fkey', 'planet', ['homeworld'], ['id'])

    # ### end Alembic commands ###
